name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push go-with-aws-tools:1.18-alpine
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: "{{defaultContext}}:1.18-alpine"
          push: ${{ github.event_name != 'pull_request' }}
          tags: docker.io/peterxj3/go-with-aws-tools:1.18-alpine
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push go-with-aws-tools:1.18-alpine
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: "{{defaultContext}}:1.19-alpine"
          push: ${{ github.event_name != 'pull_request' }}
          tags: docker.io/peterxj3/go-with-aws-tools:1.19-alpine
          labels: ${{ steps.meta.outputs.labels }}
